import Sidebar from '@/components/Sidebar'
import '@/styles/globals.css'
import { SessionProvider } from '@/components/SessionProvider'
import {getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (

          ): (

          )}
        
        </SessionProvider>
      </body>
    </html>
  )
}
