import Sidebar from '@/components/Sidebar'
import '@/styles/globals.css'
import { SessionProvider } from '@/components/SessionProvider'
import {getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/components/Login'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ): (
            <div className="flex">
          {/* Sidebar component */}
          <div className="side bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
          <Sidebar />
          </div>
          
          {/* Client provider */}
            <ClientPro

          <div className="flex-1 bg-[#31334B]">
            {children}
          </div>
        </div>
          )}
        
        </SessionProvider>
      </body>
    </html>
  )
}
